---
title: "<span style='font-size: 24px'>Initial prescribing Notification Form</style>"
output: html_document
date: '`r Sys.Date()`'
params:
    prescriber_name: NA
    prescriber_address: NA
    pt_name: NA
    pt_dob: NA
    pt_phn: NA
    pt_gender: NA
    pt_tel: NA
    pt_address: NA
    med_name: NA
    med_strength: NA
    med_dosageForm: NA
    directions_n: NA
    directions_route: NA
    directions_freq: NA
    directions_duration: NA
    rx_qty: NA
    hx: NA
    hx2: NA
    hx3: NA
    dataSx: NA
    dataRedFlags: NA
    assessment: NA
    plan: NA
    drfirst: NA
    drlast: NA
    drfax: NA
---

```{r, echo=FALSE}
knitr::asis_output(paste0(
    '##### **Name**: ', params$pt_name,'<br>**PHN**: ', params$pt_phn, '<br>', 
    '**DOB**:', params$pt_dob, '<br>**Tel**: ', params$pt_tel, '<br>',
    '**Gender**: ', params$pt_gender, '<br>',
    '**Address**: ', params$pt_address
    ))
```

---

```{r dr, echo=FALSE}
knitr::asis_output(paste0(
    "**Patient's Physician: **", params$drfirst, " ", params$drlast, 
    "<br> **Fax**: ", params$drfax
))
```

```{r header, echo=FALSE}
knitr::asis_output(paste0(
    params$pt_name, " was prescribed the following for the treatment of ", params
))
```

```{r, echo=FALSE}
knitr::asis_output(paste0('#### ', params$med_name, ' ', params$med_strength, 'mg ', params$med_dosageForm))
```

```{r, echo=FALSE}
knitr::asis_output(paste0('##### ', params$directions_n, ' ', params$directions_route, ' ', params$directions_freq, ' for ', params$directions_duration, ' days'))
```

```{r, echo=FALSE}
knitr::asis_output(paste0('##### Qty: ', params$rx_qty))
```

#### Data

```{r data, echo=FALSE}
knitr::asis_output(params$hx)
```

```{r data2, echo=FALSE}
knitr::asis_output(params$hx2)
```

```{r data3, echo=FALSE}
knitr::asis_output(params$hx3)
```

```{r data4, echo=FALSE}
knitr::asis_output(params$dataSx)
```

```{r data5, echo=FALSE}
knitr::asis_output(params$dataRedFlags)
```

#### Assessment 

```{r assessmetn, echo=FALSE}
knitr::asis_output(params$assessment)
```

#### Plan

```{r plan, echo=FALSE}
knitr::asis_output(params$plan)
```

---

<br />
<br />

```{r signature, echo=FALSE}
knitr::asis_output(paste0('##### Signature:________________________________________________<br>'))
#knitr::asis_output(params$prescriber_name)
```

```{r prescriber, echo=FALSE}
knitr::asis_output(paste0('###### **', params$prescriber_name, '**'))
```

```{r, echo=FALSE}
knitr::asis_output(paste0('##### ', params$prescriber_address))
```


---

ClinDoc-Prescribe© 