---
title: "Rx"
output: html_document
date: '`r Sys.Date()`'
params:
    prescriber_name: NA
    prescriber_address: NA
    pt_name: NA
    pt_dob: NA
    pt_phn: NA
    pt_tel: NA
    pt_gender: NA
    pt_address: NA
    med_name: NA
    med_dosageForm: NA
    directions_n: NA
    directions_route: NA
    directions_freq: NA
    directions_prn: NA
    directions_duration: NA
    directions_uot: MA
    rx_qty: NA
    rx_refills: NA
---

```{r prescriber, echo=FALSE}
knitr::asis_output(paste0('**', params$prescriber_name, '**', 
                          '<br>', params$prescriber_address
    ))
```

```{r, echo=FALSE}
knitr::asis_output(paste0(
    '**', params$pt_name, '**',
    '<br>PHN: ', params$pt_phn, '  DOB:', params$pt_dob, '  ', params$pt_gender,
    '<br>', params$pt_address, 
    '<br>', params$pt_tel
    
    ))
```

```{r, echo=FALSE}
knitr::asis_output(paste0('**', params$med_name, '**'))
```

```{r, echo=FALSE}
knitr::asis_output(paste0(params$directions_n, ' ', params$med_dosageForm, ' ', params$directions_route, ' ', params$directions_freq, 
                          params$directions_prn, ' x ', params$directions_duration, ' ', params$directions_uot))
```

```{r, echo=FALSE}
knitr::asis_output(paste0( '**Qty:** ', params$rx_qty, ' ', params$med_dosageForm, '<br>',
    ' **Refills**: ', params$rx_refills
    ))
```

---

<br />
<br />
<br />
<br />

```{r signature, echo=FALSE}
knitr::asis_output(paste0('##### Signature:________________________________________________<br>'))
knitr::asis_output(params$prescriber_name)
```

---

ClinDoc-Prescribe© 
